version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: Danielito_0811
      POSTGRES_DB: base_de_datos_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/base_de_datos_demo
      SPRING_DATASOURCE_USERNAME: daniel
      SPRING_DATASOURCE_PASSWORD: Danielito_0811
    depends_on:
      - db

volumes:
  postgres_data:
